ticker = 'NVDA' # ticker to analyze
crypto = 'BINANCE:ETHUSDT' # crypto to analyze
interval = 'D' # less than a day means only a month of data, valid options are '1' '5' '15' '30' '60' 'D' 'W' 'M'
transaction_fee = 0.001 # 2% transaction fee default
starting_money = 1000 # $1,000 default
investment = 50 # $50 default
adx_sell = 40 # default 40
adx_buy = 20 # default 20
adx_range = 14 # default 14
stoch_sell = 80 # default 80
stoch_buy = 20 # default 20
stoch_range = 14 # default 14
optimize_params = True # default False
optimization_depth = 100 # default 100
